[package]
name = "rsolver"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.3", features = ["derive"] }
strum = { version = "0.25.0", features = ["derive"] }
derive-try-from-primitive = "1.0.0"
rand = "0.8.5"


[profile.dev]
opt-level = 3
